### ISSUE TITLE
contribute please

### ISSUE THREAD

**Issue by RahulPalve** [RahulPalve/ClipBoard-django-pastebin#1]

**Comment by Jan200101** [comment]
anything specific that needs to be done?

**Comment by RahulPalve** [comment]
Ahh actually no , but it will really Better if someone can write test cases.

**Comment by bansaljas** [comment]
Do you want any enhancements to be done?

**Comment by raja-d** [comment]
Hi, I am new to open source. Can I contribute? Also I might need a little guidance.
